### ISSUE TITLE
error from dbus wrapper

### ISSUE THREAD

**Issue by vanem** [software-jessies-org/jessies#37]
When I try to run terminator on Ubuntu 18.04, I get this error:

Traceback (most recent call last):
  File "/usr/bin/x-terminal-emulator", line 83, in <module>
    from terminatorlib import ipc
  File "/usr/share/terminator/terminatorlib/ipc.py", line 31, in <module>
    class DBusService(Borg, dbus.service.Object):
  File "/usr/share/terminator/terminatorlib/ipc.py", line 62, in DBusService
    @dbus.service.method(BUS_NAME, in_signature='a{ss}')
  File "/usr/lib/python2.7/dist-packages/dbus/decorators.py", line 155, in method
    validate_interface_name(dbus_interface)
ValueError: Invalid interface or error name 'net.tenshu.Terminator2-0xa48cd7ee82546f': contains invalid character '-'

Workaround is to run "terminator -u"

**Comment by martindorey** [comment]
Sorry but https://github.com/software-jessies-org/jessies/wiki/TerminatorFAQ#this-is-not-gnome-terminator ("tenshu" is a give away that it's Chris Jones's - that's his domain).
